- name: Create directory for Datahub
  file:
    path: "{{ wazuh_dir }}"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0755"

- name: Clone wazuh repository
  git:
    repo: "{{ wazuh_repo_url }}"
    dest: "{{ wazuh_dir }}"
    version: "v{{ wazuh_version }}"
    single_branch: true
    force: true
  register: clone_result

- name: Notify about cloning result
  debug:
    msg: "wazuh repository cloned to {{ wazuh_dir }}"
  when: clone_result.after is defined

- name: generate ssl
  command: docker compose -f {{wazuh_dir}}/single-node/generate-indexer-certs.yml run --rm generator

- name: Gracefully start Datahub services using Docker Compose
  community.docker.docker_compose_v2:
    project_src: "{{ wazuh_dir }}/single-node"
    files:
      - "docker-compose.yml"
    state: present
    pull: missing
    build: always
    recreate: always

- name: Wait for Datahub startup
  pause:
    seconds: 15

- name: Verify Datahub service is up
  uri:
    url: http://127.0.0.1:443
    method: GET
    status_code: 200 # Expected HTTP status code
